In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

from selenium import webdriver
from bs4 import BeautifulSoup
import time
from selenium.webdriver.chrome.options import Options # オプションを使うために必要

In [2]:
data_path="Wisdom_Long_List 20210917.xlsx"

In [3]:
df1=pd.read_excel(data_path,sheet_name="AU Main Long List")
df1.head(30)

,No.,Person in Charge,Company Name,Quick Summary,Company Overview,Good Candidate Reason,Level of Recommendation\n(✗- ✓✓✓),Type of Company,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Market Cap \n(AUD Mn) \n(as of July 13th),Registered Capital\n (AUD Mn),Shareholders,Website,Contact Available?,Contacted?,Met?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,System Integrator,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ERP only,ERP & Others,Others Only \n(comment),...,Total Assets,Total Liabilites,Net Assets,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Minato,Acclimation Pty Ltd,capgemini company,"Acclimation, a Capgemini company, is an SAP so...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.acclimation.com/,NaN,NaN,NaN
3,2,Minato,Advanced Training Pty Ltd,NaN,Advanced Training is dedicated to IT technical...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://advancedtraining.com.au/,NaN,NaN,NaN
4,3,Minato,ASCENDER CLOUD SERVICES PTY LTD,NaN,Ascender focuses on creating prosperity throug...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ascenderhcm.com/,NaN,NaN,NaN
5,4,Minato,ASG Group Limited,NRI company,"For over two decades, ASG has been providing b...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.asggroup.com.au/,NaN,NaN,NaN
6,5,Minato,Basis Expert Consulting Services,NaN,Basis Expert Consulting Services is a team of ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.beeceeyes.com/,NaN,NaN,NaN
7,6,Minato,BiTech Group,NaN,BiTech Group is one of Australian’s top SAP se...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://bitech.com.au/,NaN,NaN,NaN
8,7,Minato,Bluetree Solutions Pty Ltd,NaN,Bluetree is an Award Winning Consulting Compan...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://bluetree.com.au/,NaN,NaN,NaN
9,8,Minato,Bourne Digital,NaN,Bourne Digital are a specialist provider of SA...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.bournedigital.com.au/,NaN,NaN,NaN
10,9,Minato,CitySoft Consulting,NaN,CitySoft is an awarded Sage and SAP partner an...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://citysoft.net.au/,NaN,NaN,NaN
11,10,Minato,CJV Partners Pty Limited,NaN,CJV Partners is an SAP silver partner. We offe...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.cjvpartners.com/,NaN,NaN,NaN
12,11,Minato,CloudFactory.co,NaN,We are a passionate and long standing consulti...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.cloudfactory.co/,NaN,NaN,NaN
13,12,Minato,CompliantERP,NaN,CompliantERP is an SAP silver partner providin...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://complianterp.com/,NaN,NaN,NaN
14,13,Minato,DalRae Solutions Pty Ltd,NaN,"Founded in 2015, DalRae Solutions is a team of...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://dalraesolutions.com/,NaN,NaN,NaN
15,14,Minato,Discovery Consulting Group Pty Ltd,NaN,Discovery Consulting provides SAP and SuccessF...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.discoveryconsulting.com.au/,NaN,NaN,NaN
16,15,Minato,DXC Technology,Not Australian company,DXC provide a full spectrum of SAP-based solut...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.dxc.com/au/en,NaN,NaN,NaN
17,16,Minato,DyFlex Solutions,NaN,DyFlex is recognised as one of the leading SAP...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://dyflex.com.au/,NaN,NaN,NaN
18,17,Minato,Emisha A/NZ Pty. Ltd.,NaN,Emisha is a data management and analytics comp...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.emishaglobal.com/,NaN,NaN,NaN
19,18,Minato,Enterprise Wide Pty Ltd,NaN,Enterprise Wide is a professional services org...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.enterprisewide.com/,NaN,NaN,NaN
20,19,Minato,Environmental Resources Management Australia P...,NaN,As the largest global pure play sustainability...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.erm.com/,NaN,NaN,NaN
21,20,Minato,EPI-USE Australia Pty Ltd,NaN,With over 30-years’ experience in the delivery...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.epiuse.com/,NaN,NaN,NaN
22,21,Minato,excelerateds2p - APAC,NaN,"At excelerateds2p, we work with innovative org...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.excelerateds2p.com/,NaN,NaN,NaN
23,22,Minato,FAIR Consulting Group Pty Ltd,NaN,Our business is focused on crafting digital ex...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://faircg.com/,NaN,NaN,NaN
24,23,Minato,GO1 Pty Ltd,NaN,Go1 provides SAP SuccessFactors customers acce...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.go1.com/,NaN,NaN,NaN
25,24,Minato,Happiest Minds Technologies Pvt Ltd,NaN,Happiest Minds enables Digital Transformation ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.happiestminds.com/,NaN,NaN,NaN
26,25,Minato,HR Path,NaN,HR Path helps companies for who Human Experien...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.hr-path.com/,NaN,NaN,NaN
27,26,Minato,Infosys Australia - Portland,NaN,Infosys is Global Strategic Services Partner o...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.infosys.com/,NaN,NaN,NaN
28,27,Minato,Integeo Pty Ltd,NaN,Integeo is strategically placed to provide inn...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.integeo.com/,NaN,NaN,NaN
29,28,Minato,JAF Solutions,NaN,JAF Solutions has a longstanding proven track ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://jafs.com.au/,NaN,NaN,NaN

In [4]:
df1.columns

Index(['No.', 'Person in Charge', 'Company Name', 'Quick Summary',
       'Company Overview', 'Good Candidate Reason',
       'Level of Recommendation\n(✗- ✓✓✓)', 'Type of Company', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Year Established',
       'No. of Employees\n(Estimated)', 'Partners/Technology', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'D&B URL',
       'Financials (USD Mn)', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Market Cap \n(AUD Mn) \n(as of July 13th)',
       'Registered Capital\n (AUD Mn)', 'Shareholders', 'Website',
       'Contact Available?', 'Contacted?', 'Met?'],
      dtype='object')

In [6]:
series_mic=df1["Unnamed: 15"]
series_mic[series_mic.notna()]

1      Oracle
5           ✓
16          ✓
27          ✓
39          ✓
        ...
288         ✓
289         ✓
290         ✓
291         ✓
292         ✓
Name: Unnamed: 15, Length: 237, dtype: object

In [7]:
#print(len(df1),len(df1[334:]))
df1[190:213]

,No.,Person in Charge,Company Name,Quick Summary,Company Overview,Good Candidate Reason,Level of Recommendation\n(✗- ✓✓✓),Type of Company,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Market Cap \n(AUD Mn) \n(as of July 13th),Registered Capital\n (AUD Mn),Shareholders,Website,Contact Available?,Contacted?,Met?
190,189,Hosoda,HANSEN CORPORATION PTY. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,190,Hosoda,The Centre for Excellence Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,191,Hosoda,Elwyn Consulting Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,192,Hosoda,Ascender Pay Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,193,Hosoda,VOIP Distribution Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,194,Hosoda,Noveix Systems Pty Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,195,Hosoda,Reed International Books Australia Pty Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,196,Hosoda,Westcon Group European Operations Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,197,Hosoda,Rinami Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,198,Hosoda,Global IT Factory Pty. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,199,Hosoda,Fusion Applications Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,200,Hosoda,Larsen & Toubro Infotech Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,201,Hosoda,Logical Technologies Pty Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,202,Hosoda,Iliveit Australia Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,203,Hosoda,Diamond Key International Pty Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,204,Hosoda,Atos International SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,205,Hosoda,Data#3 Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,206,Hosoda,Fusion5 Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,207,Hosoda,Invictus Partners Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,208,Hosoda,Delivery Centric Pty ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,209,Hosoda,SecureCo Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,210,Hosoda,UNIFIED DESIGN PTY LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,211,Hosoda,ESRI Australia Pty Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import requests
from bs4 import BeautifulSoup
import time

def func(i,url):
    time.sleep(2) 
    
    option = Options()                          # オプションを用意
    option.add_argument('--headless')           # ヘッドレスモードの設定を付与
    driver = webdriver.Chrome()
    driver.get(url)

    soup = BeautifulSoup(driver.page_source, features="html.parser")
    profile=soup.find("span",{"class":"company_summary"}).text
    driver.close()
           
    df1.loc[i,"profile"]=profile
    
    print(i,"：正常終了")

In [9]:
mic_df=df1[190:213]

for i,row in mic_df[mic_df["D&B URL"].notna()].iterrows():
    url=row["D&B URL"]
    try:
        func(i,url)
    except:
        print(i)

190 ：正常終了
191 ：正常終了
192 ：正常終了
193 ：正常終了
194 ：正常終了
195 ：正常終了
196 ：正常終了
197 ：正常終了
198 ：正常終了
199 ：正常終了
200 ：正常終了
201 ：正常終了
202 ：正常終了
203 ：正常終了
204 ：正常終了
205 ：正常終了
206 ：正常終了
207 ：正常終了
209 ：正常終了
210 ：正常終了
211 ：正常終了
212 ：正常終了

In [10]:
df1[df1["profile"].notna()].profile

190    HANSEN CORPORATION PTY. LTD. is located in Don...
191    THE CENTRE FOR EXCELLENCE PTY. LIMITED is loca...
192    ELWYN CONSULTING PTY LTD is located in RANDWIC...
193    ASCENDER PAY PTY LTD is located in Mascot, NEW...
194    VOIP DISTRIBUTION PTY LTD is located in Artarm...
195    NOVEIX SYSTEMS PTY LIMITED is located in Terre...
196    REED INTERNATIONAL BOOKS AUSTRALIA PTY LIMITED...
197    WESTCON GROUP EUROPEAN OPERATIONS LIMITED is l...
198    RINAMI PTY LTD is located in VARSITY LAKES, QU...
199    GLOBAL IT FACTORY PTY. LTD. is located in MELB...
200    FUSION APPLICATIONS PTY LTD is located in Pert...
201    \n   Larsen & Toubro Infotech (L&T Infotech) i...
202    I LOGICAL TECHNOLOGIES PTY LIMITED is located ...
203    TEEG AUSTRALIA PTY LTD is located in North Syd...
204    DIAMOND KEY PTY. LTD. is located in CARLTON SO...
205    Atos SE is the third-biggest IT services compa...
206    DATA#3 LIMITED. is located in TOOWONG, QUEENSL...
207    FUSION5 PTY LTD is located in Melbourne, VICTO...
209    DELIVERY CENTRIC - TECHNOLOGY SERVICES PTY LTD...
210    SECURECO PTY LTD is located in NORTH SYDNEY, N...
211    UNIFIED DESIGN PTY LTD is located in STRATHFIE...
212    ESRI AUSTRALIA DEFENCE PTY LTD is located in B...
Name: profile, dtype: object

In [11]:
tmp=df1[df1["profile"].notna()].loc[190,"profile"]
tmp

'HANSEN CORPORATION PTY. LTD. is located in Doncaster, VICTORIA, Australia and is part of the Computer Systems Design and Related Services Industry. HANSEN CORPORATION PTY. LTD. has 1,000 total employees across all of its locations and generates $198.75 million in sales (USD). (Employees figure is estimated). There are 33 companies in the HANSEN CORPORATION PTY. LTD. corporate family.'

In [12]:
import re

earn_pattern = r"([0-9]+)\.([0-9]+) million"
employ_pattern = r"([0-9]+) employee"
m = re.search(earn_pattern, tmp)
print(m)

<re.Match object; span=(246, 260), match='198.75 million'>

In [21]:
for i,row in df1[df1["profile"].notna()].iterrows():
    tmp=row["profile"]
    
    earn_pattern1 = r"([0-9]+)\,([0-9]+)\.([0-9]+) million"
    earn_pattern2 = r"([0-9]+)\.([0-9]+) million"
    earn_pattern3 = r"([0-9]+)\,([0-9]+) in sales"
    earn_pattern4 = r"([0-9]+)\.([0-9]+) billion"
    
    employ_pattern2 = r"([0-9]+) ([a-z]+) employee"
    employ_pattern1 = r"([0-9]+),([0-9]+) ([a-z]+) employee"
    employ_pattern4 = r"([0-9]+) employee"
    employ_pattern3 = r"([0-9]+),([0-9]+) employee"
    
    m1 = re.search(earn_pattern1, tmp)
    m2 = re.search(earn_pattern2, tmp)
    m3 = re.search(earn_pattern3, tmp)
    m4 = re.search(earn_pattern4, tmp)
    
    n1 = re.search(employ_pattern1, tmp)
    n2 = re.search(employ_pattern2, tmp)
    n3 = re.search(employ_pattern3, tmp)
    n4 = re.search(employ_pattern4, tmp)
    
    n=n1 if n1 else n2 if n2 else n3 if n3 else n4
    m=m1 if m1 else m2 if m2 else m3 if m3 else m4
    
    try:
        print(i,"earn : ",m[0],"employ : ",n[0])
        #print(i,"employ : ",n[0].split()[0])
        #print(i,"earn : ",m[0])
    except:
        if m:
            print(i,"earn : ",m[0],row["D&B URL"])
        elif n:
            print(i,"employ : ",n[0],row["D&B URL"])
        else:
            print(i,row["D&B URL"])

190 earn :  198.75 million employ :  1,000 total employee
191 earn :  845,578 in sales employ :  4 employee
192 earn :  559,000 in sales employ :  4 employee
193 earn :  155.33 million employ :  393 employee
194 earn :  13.14 million employ :  46 employee
195 earn :  1.10 million employ :  6 employee
196 earn :  162.45 million employ :  600 employee
197 earn :  1.24 billion employ :  1,149 employee
198 earn :  2.21 million employ :  10 employee
199 earn :  3.55 million employ :  25 employee
200 earn :  3.06 million employ :  9 employee
201 https://www.dnb.com/business-directory/company-profiles.larsen__toubro_infotech_limited.2d756972fd6f966c80b7515a7d3ea361.html
202 earn :  702,208 in sales employ :  3 employee
203 earn :  201.05 million employ :  2,323 total employee
204 earn :  1.26 million employ :  4 employee
205 https://www.dnb.com/business-directory/company-profiles.atos_se.19bc1728c068998305248bacba168955.html
206 earn :  1.26 billion employ :  1,144 employee
207 earn :  14.94 million employ :  201 employee
209 earn :  1.03 million employ :  4 employee
210 earn :  2.06 million employ :  23 employee
211 earn :  474,360 in sales employ :  4 employee
212 earn :  65.35 million employ :  212 total employee

In [22]:
import openpyxl
openpyxl.Workbook()
wb=openpyxl.load_workbook(data_path)
sheet = wb["AU Main Long List"]
sheet

In [30]:
for i,row in df1[df1["profile"].notna()].iterrows():
    print(i,"##############################")
    tmp=row["profile"]
    
    earn_pattern1 = r"([0-9]+)\,([0-9]+)\.([0-9]+) million"
    earn_pattern2 = r"([0-9]+)\.([0-9]+) million"
    earn_pattern3 = r"([0-9]+)\,([0-9]+) in sales"
    earn_pattern4 = r"([0-9]+)\.([0-9]+) billion"
    
    employ_pattern2 = r"([0-9]+) ([a-z]+) employee"
    employ_pattern1 = r"([0-9]+),([0-9]+) ([a-z]+) employee"
    employ_pattern4 = r"([0-9]+) employee"
    employ_pattern3 = r"([0-9]+),([0-9]+) employee"
    
    m1 = re.search(earn_pattern1, tmp)
    m2 = re.search(earn_pattern2, tmp)
    m3 = re.search(earn_pattern3, tmp)
    m4 = re.search(earn_pattern4, tmp)
    
    n1 = re.search(employ_pattern1, tmp)
    n2 = re.search(employ_pattern2, tmp)
    n3 = re.search(employ_pattern3, tmp)
    n4 = re.search(employ_pattern4, tmp)
    
    n=n1 if n1 else n2 if n2 else n3 if n3 else n4
    m=m1 if m1 else m2 if m2 else m3 if m3 else m4
    
    if n:
        out1=n[0].split()[0]
        sheet.cell(column=14,row=i+2).value = out1
        print("1",out1)
    
    if m:
        if "million" in m[0]:
            out2=" ".join(m[0].split()[:2])
            sheet.cell(column=22,row=i+2).value = out2
        
        elif "billion" in m[0]:
            out2=" ".join(m[0].split()[:2])
            sheet.cell(column=22,row=i+2).value = out2
         
        elif "sale" in m[0]:
            out2=m[0].split()[0]
            sheet.cell(column=22,row=i+2).value = out2
        print("2",out2)
        
    if m:
        if "million" in m[0]:
            out2=m[0].split()[0]
            sheet.cell(column=22,row=i+2).value = out2

        elif "billion" in m[0]:
            out2=int(float(m[0].split()[0]))*1000
            sheet.cell(column=22,row=i+2).value = out2

        elif "sale" in m[0]:
            a=int(float("".join(m[0].split()[0].split(","))))
            out2="{:.2f}".format(a/1000000)
            sheet.cell(column=22,row=i+2).value = out2

190 ##############################
1 1,000
2 198.75 million
191 ##############################
1 4
2 845,578
192 ##############################
1 4
2 559,000
193 ##############################
1 393
2 155.33 million
194 ##############################
1 46
2 13.14 million
195 ##############################
1 6
2 1.10 million
196 ##############################
1 600
2 162.45 million
197 ##############################
1 1,149
2 1.24 billion
198 ##############################
1 10
2 2.21 million
199 ##############################
1 25
2 3.55 million
200 ##############################
1 9
2 3.06 million
201 ##############################
202 ##############################
1 3
2 702,208
203 ##############################
1 2,323
2 201.05 million
204 ##############################
1 4
2 1.26 million
205 ##############################
206 ##############################
1 1,144
2 1.26 billion
207 ##############################
1 201
2 14.94 million
209 ##############################
1 4
2 1.03 million
210 ##############################
1 23
2 2.06 million
211 ##############################
1 4
2 474,360
212 ##############################
1 212
2 65.35 million

In [31]:
wb.save("Sample.xlsx")